### ISSUE TITLE
New taxonomy for 2024

### ISSUE THREAD

**Issue by pvmagacho-nde** [manusimidt/py-xbrl#138]
Taxonomy missing:

_The taxonomy with namespace http://fasb.org/srt/2024 could not be found._

**Comment by pvmagacho-nde** [comment]
Hi @manusimidt  missed one: _The taxonomy with namespace http://fasb.org/us-gaap/2024 could not be found._

**Comment by manusimidt** [comment]
Thanks for the hint. Probably there are still thousands of XBRL documents out there which are using some taxonomy which is not correctly referenced by a schema URL.
In the future I want to rely on mappings provided by authority (i.e. SEC https://www.sec.gov/info/edgar/edgartaxonomies.xml). However, these of course also do not cover all used taxonomies. But it would reduce the effort for me to update a list every year :D
