### ISSUE TITLE
Start getting 403 errors from sec.gov

### ISSUE THREAD

**Issue by Evgeniy-** [manusimidt/py-xbrl#144]
**XBRL document**
"https://www.sec.gov/Archives/edgar/data/0000320193/000032019321000105/aapl-20210925.htm"
or any other document from sec.gov

**Describe the bug**
Since recently (this month)  running  parse_instance or parse_xbrl_url functions give 403 errors on Sec.gov URLs

MaxRetryError: HTTPSConnectionPool(host='[www.sec.gov](https://www.sec.gov/)', port=443): Max retries exceeded with url: /Archives/edgar/data/0000320193/000032019321000105/aapl-20210925.htm (Caused by ResponseError('too many 403 error responses'))

Tried on several machines (home/work/cloud) - same issue. 

example code:

https://py-xbrl.readthedocs.io/en/latest/usage.html#online

**Comment by manusimidt** [comment]
Hey seems like the SEC is blocking your network requests. Have you specified your header correctly?:
```python
cache.set_headers({'From': 'YOUR@EMAIL.com', 'User-Agent': 'your-app/version'})
```

**Comment by manusimidt** [comment]
You can consult this page for more information: 
https://www.sec.gov/search-filings/edgar-search-assistance/accessing-edgar-data

- Current max request rate: 10 requests/second => make sure to set time.sleeps()
- Please declare your user agent in request headers

**Comment by Evgeniy-** [comment]
Hi, thanks for reply! It all worked up until August. Today I've tried all kind of headers (including Chrome/Firefox headers)  in combination with different machines / IP adresses. Nothing worked. Is it really only me having this issue?

**Comment by Evgeniy-** [comment]
> User-Agent: | Sample Company Name AdminContact@<sample company domain>.com

Setting User-Agent to my e-mail address solved the issue.

**Comment by blakewest** [comment]
fwiw, I also had to set the User-Agent to my email. Otherwise I was getting the 403 errors. (ie. the info right in the docs did not work)
