### ISSUE TITLE
Make delay in HTTP Cache more intelligent

### ISSUE THREAD

**Issue by manusimidt** [manusimidt/py-xbrl#18]
Currently the HTTPCache waits the specified time, regardless of whether another request follows.
https://github.com/manusimidt/xbrl_parser/blob/5a1b3882e8b65f7815bbc330c9c010169c195951/xbrl_parser/cache.py#L77

It should have at least an internal clock that counts the number of millisecs between two requests.

**Comment by mrx23dot** [comment]
Done in https://github.com/manusimidt/py-xbrl/pull/65
