### ISSUE TITLE
Rounding error

### ISSUE THREAD

**Issue by mrx23dot** [manusimidt/py-xbrl#42]
Parsing
   https://www.sec.gov/Archives/edgar/data/0000320193/000032019321000056/aapl-20210327.htm

for 
    fact.concept.name == 'UnrecognizedTaxBenefits'

results in
   fact.value == 16899999999.999998

source seems to have it correctly:

"us-gaap:UnrecognizedTaxBenefits" scale=3D"9" id=3D"id3VybDovL2RvY3MudjEvZG=
9jOmRhZDhkZWU5YWJlYTQ1NDM4YTBlMDI0ZmZiODE1ZDFhL3NlYzpkYWQ4ZGVlOWFiZWE0NTQzO=
GEwZTAyNGZmYjgxNWQxYV80OS9mcmFnOjAwOWNkNTU0YjAyNzQ4MjI5NmU2MjliY2MyNDkwMDQ3=
L3RleHRyZWdpb246MDA5Y2Q1NTRiMDI3NDgyMjk2ZTYyOWJjYzI0OTAwNDdfMTE3_2dc3aa0b-3=
02e-4999-9819-1ab85e1929c2">**16.9**</ix:nonfraction> Billion

**Comment by manusimidt** [comment]
Thanks, i could replicate the issue you are describing and will work on a fix 👍🏼
