### ISSUE TITLE
undefined entity exception

### ISSUE THREAD

**Issue by mrx23dot** [manusimidt/py-xbrl#58]
When parsing:
https://www.sec.gov/Archives/edgar/data/0001764013/000121390019023173/f10q0919_healthsciencesacq.htm

I get exception:
undefined entity: line 15, column 172

via
inst = XbrlParser(cache).parse_instance(url)

py-xbrl==2.0.7

**Comment by manusimidt** [comment]
![image](https://user-images.githubusercontent.com/29599104/128840541-e4ebf1c5-a456-4f5e-9578-862a4816417e.png)

The file `f10q0919_healthsciencesacq.htm` is just a normal HTML document and thus can not be parsed by py-xbrl.
Please use the corresponding Instance Document for this particular filing:
https://www.sec.gov/Archives/edgar/data/1764013/000121390019023173/hsac-20190930.xml
