### ISSUE TITLE
Support nested Facts

### ISSUE THREAD

**Issue by mrx23dot** [manusimidt/py-xbrl#59]
In
https://www.sec.gov/ix?doc=/Archives/edgar/data/0001439725/000156459020056735/bdsx-10q_20200930.htm

for
DocumentPeriodEndDate

returns 
'September 30,'

ctx
![ctx](https://user-images.githubusercontent.com/4163396/128930902-8dae1e49-3749-4282-9736-a8e62f1de390.jpg)

but web view shows:
September 30, 2020

Works on others.

(not critical, only using it for sanity checking)

**Comment by mrx23dot** [comment]
some others:
https://www.sec.gov/ix?doc=/Archives/edgar/data/0001122904/000156459020035177/ntgr-10q_20200628.htm
https://www.sec.gov/ix?doc=/Archives/edgar/data/0001439725/000156459020056735/bdsx-10q_20200930.htm
https://www.sec.gov/ix?doc=/Archives/edgar/data/0001720592/000156459020024317/rpay-10q_20200331.htm

**Comment by manusimidt** [comment]
I understand why this can be confusing, but in the example you provided, the concept `dei:DocumentPeriodEndDate` really only holds the value September 30. 

Nested facts are currently not supported by the libary, but this is one of the features I really want to implement in the near future.

```xml
<ix:nonNumeric 
	id="F_000003" 
	name="dei:DocumentPeriodEndDate" 
	contextRef="C_0001439725_20200101_20200930" 
	format="ixt:datemonthdayyearen">September 30, 
		<ix:nonNumeric 
			id="F_000004" 
			name="dei:DocumentFiscalYearFocus" 
			contextRef="C_0001439725_20200101_20200930">2020
		</ix:nonNumeric>
</ix:nonNumeric>
```

> See line 4192 in www.sec.gov/Archives/edgar/data/0001439725/000156459020056735/bdsx-10q_20200930.htm


For now I suggest to use the context of the fact tagged with the concept `dei:DocumentPeriodEndDate` to get the period date of the document.

**Comment by mrx23dot** [comment]
Fact end date should also work then.
Is there a way to tell if a fact is incomplete (nested)?

What about these issues?

Weirdly it doesn't even find DocumentPeriodEndDate in: (web view shows it)
https://www.sec.gov/Archives/edgar/data/0001583107/000155837020010023/tbph-20200630x10q.htm

Also doesn't find StockholdersEquity in (it's highlighted in web view):  (shouldn't be nested)
https://www.sec.gov/ix?doc=/Archives/edgar/data/0001390777/000139077721000037/bk-20201231.htm

Thank you!
