### ISSUE TITLE
Bug: instance.json('my-file.json') 

### ISSUE THREAD

**Issue by ajmed** [manusimidt/py-xbrl#89]
The `XbrlInstance.json(self, file_path: str = None, override_fact_ids: bool = True)` function does not respect the file_path argument. Specifically, if the file_path is specified it writes the json object to a hardcoded filepath, `data.json` instead of the file_path specified.

```python
if file_path:
    with open('data.json', 'w') as f:
        return json.dump(json_dict, f)
else:
    return json.dumps(json_dict)
```

**Comment by manusimidt** [comment]
Oh yeah, that's an obvious bug, thanks!
